const Product_id = "88e67328-3b20-413e-b6e1-010b48fa7bc9";
const Client_id = "spa_rosas_admin_panel";
const statusArray = [
  "Created in db",
  "Creating",
  "Creating",
  "Created As Active",
  "Activating",
  "Activating",
  "Active",
  "Deactivating",
  "Deactivating",
  "Deactivate",
  "Deleting",
  "Deleting",
  "Deleted",
];

const statusOpacity = [
  "35",
  "15",
  "15",
  "35",
  "15",
  "15",
  "35",
  "15",
  "15",
  "35",
  "15",
  "15",
  "35",
];
const statusColor = [
  "#155dd7",
  "#155dd7",
  "#155dd7",
  "#00a675",
  "#00a675",
  "#00a675",
  "#00a675",
  "#eda100",
  "#eda100",
  "#eda100",
  "#ff0f5f",
  "#ff0f5f",
  "#ff0f5f",
];
const statusIcon = [
  "pi-user-plus",
  "pi-user-plus",
  "pi-user-plus",
  "pi-check-circle",
  "pi-check-circle",
  "pi-check-circle",
  "pi-check-circle",
  "pi-exclamation-triangle",
  "pi-exclamation-triangle",
  "pi-exclamation-triangle",
  "pi-trash",
  "pi-trash",
  "pi-trash",
];
export {
  Product_id,
  Client_id,
  statusArray,
  statusColor,
  statusIcon,
  statusOpacity,
};
